name: Push Draft Branch to Other Repo

on:
  push:
    branches:
      - draft # Triggers whenever commits are pushed to the 'draft' branch

jobs:
  push-to-another-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history so tags and full branch history copy over

      - name: Push to Destination Repository
        uses: repo-sync/github-sync@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_repo_token: ${{ secrets.BETA_REPO_TOKEN }}
          destination_repository: "stanfordfast/beta-website"
          source_branch: "draft"
          destination_branch: "master" # Change if you want it named differently in the destination